# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  release:
    types: [published]
  push:
    tags:        
      - v*
    branches: [ main, dev, mac]
  pull_request:
    branches: [ main ]
  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  build-app:
    name: Build Base Packages
    runs-on: macos-latest
    timeout-minutes: 3

    strategy:
      matrix:
        node-version: [16.x]
        ARCH: ['x64']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2

      - name: Test
        run: |
          wget https://downloads.getfiddler.com/mac-arm64/Fiddler%20Everywhere%206.2.0.dmg -O fiddler.dmg
          yes y | hdiutil attach fiddler.dmg -mountpoint "/Volumes/fiddler"
          ls -l /Volumes
          mkdir -p tmp
          cp -R /Volumes/fiddler/* ./tmp
          hdiutil detach "/Volumes/fiddler"
          cd "tmp/Fiddler Everywhere.app/Contents"
          # tmp/Fiddler Everywhere.app/Contents

          cd Frameworks
          # tmp/Fiddler Everywhere.app/Contents/Frameworks

          rm libfiddler.dylib
          wget https://github.com/project-yui/Yui-patch/releases/download/v1.1.3/yui-fiddler-mac-arm64-v1.1.3.dylib -O libfiddler.dylib
          
          cd ..
          # tmp/Fiddler Everywhere.app/Contents

          mv Resources/app/out/main.js Resources/app/out/main.original.js
          cat ../../../server/index.js > Resources/app/out/main.js
          cat Resources/app/out/main.original.js >> Resources/app/out/main.js
          cp -R ../../../server/file Resources/app/out
          # ./MacOS/Fiddler\ Everywhere
          p=$(pwd)
          cd ../../..
          cp -R tmp/* /Applications/
          node tools/mac-test.js "/Applications/Fiddler Everywhere.app/Contents"